### ISSUE TITLE
Add Pupa database as a Docker Compose service

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#2128] opened 2018-02-05 21:38 UTC
Right now, Docker Compose contains a MongoDB, but not a Pupa DB. And it's not very easy to connect the `scrape` service to a local Postgres, to boot.

Add a service to the `docker-compose.yml` that contains a Pupa Postgres, and link that to the `scrape` service/container.

**Comment by jamesturk** [comment] 2018-02-14 16:15
dupe of #1851

**Closed by jamesturk** 2018-02-14 16:15 UTC
