### ISSUE TITLE
MO Committee Members are incorrect

### ISSUE THREAD

**Issue by Wizofgoz** [openstates/openstates#1319] opened 2017-02-01 22:06 UTC
https://openstates.org/api/v1//committees/MOC000028/?state=mo&apikey=xxxxx
vs
http://house.mo.gov/CommitteeList.aspx (Budget Committee)

Some don't even show in the Legislators list such as:
Sue Allen
Eric Burlison
Lincoln Hough
and Caleb Jones

**Comment by jamesturk** [comment] 2017-02-04 04:48
scraper needs to be revisited, is failing quickly

**Comment by jonConerly** [comment] 2017-02-07 04:25
Opps, looks like somebody already grabbed this one.  Closing my PR.

**Closed** 2017-02-07 04:44 UTC
Labels: in progress

**Comment by Wizofgoz** [comment] 2017-02-07 16:47
It looks like the data is still not correct,

The example links still don't match but the names I had listed before are showing now.

**Comment by loandy** [comment] 2017-02-10 19:44
I'll go ahead and take a look.

**Comment by loandy** [comment] 2017-02-14 00:37
I'm able to get the correct committee memberships when running the scraper locally, but this may have been caused by a scraper failure. @jamesturk or @mileswwatkins might be able to say more in that regard.

Poking around in the MO scrapers, it looks like the vote scraper isn't really doing anything (and potentially conflicting with the vote scraping in the bill scraper) and maybe should be shut off for the time being.

**Comment by jamesturk** [comment] 2017-02-14 00:40
Looks like MO was just running leg & bills, I've turned comms on to run it
tonight.  Votes is indeed off, but we should look closer at why there are
two.

**Comment by loandy** [comment] 2017-02-16 22:35
Sorry, meant to respond to this earlier: I took a long look at behavior between the bill and vote scrapers, and the vote scraper only seems to be confounding the scraping without adding anything. Currently working on properly resolving the chamber resolution for vote actions within the bill scraper.
