### ISSUE TITLE
CO - Too many legislators in json file

### ISSUE THREAD

**Issue by Jelfff** [openstates/openstates#1617] opened 2017-04-05 14:20 UTC
The most recent json file available for Colorado includes timestamps like 4/3 8:13.
A count of the ‘active’ entries in that json file shows:
json_state_house_seats = 66.  The correct value = 65
json_state_senate_seats = 36.  The correct value = 35

I grabbed the json file with this API call:
https://openstates.org/api/v1/legislators/?state=co

Joseph Elfelt

**Comment by TroyLDay** [comment] 2017-04-07 17:18
There is a dupe of Angela Williams which should be Larry Crowder for district 35.  I joined to find out where/how/who to update the data.  Is that done through automation/scraping?

**Comment by In-vincible** [comment] 2017-04-07 17:27
@jamesturk guess data tool is going to be handy !

**Comment by TroyLDay** [comment] 2017-04-07 18:47
Data tool?

**Comment by Jelfff** [comment] 2017-04-09 00:17
In addition to the needed tweak that Troy reported, lower district 15 should not have 2 people.
https://openstates.org/api/v1/legislators/?state=co&chamber=lower&district=15
Dave Williams is in the output twice.

**Closed** 2017-04-10 02:59 UTC
