### ISSUE TITLE
TX: Some legislator names are not properly utf8 encoded (upper)

### ISSUE THREAD

**Issue by richardm** [openstates/openstates#1294] opened 2017-01-23 05:27 UTC
This appears to only affect senators. Representatives are properly encoded.

Specifically, these two:
Jose Rodriguez (District 29):
https://openstates.org/api/v1/legislators/TXL000701

Jose Menendez (District 26):
https://openstates.org/api/v1/legislators/TXL000711

**Comment by jonConerly** [comment] 2017-01-24 05:21
The problem is that the server is not sending back an encoding in the response header and only setting it correctly with the <meta> tag in the source of the HTML.  The method that is being used to parse the directory page, _scrape, lxml.html.fromstring() is not using a HTMLParser so it will be relying on the requests encoder.  Requests also attempts to autodetect the encoding by looking at the server response, due missing encoding type from the server, requests sets encoding to ISO-8859-1.  The encoding type can be overrided and statically assigned to any value(slightly risky for a dynamic page); requests can also decent encoding detection by apparent_encoding.

I can put a PR to solve the issue using apparent_encoding

**Comment by jamesturk** [comment] 2017-01-25 02:12
this is merged, after next TX PR we'll wind up with two duplicate legislators that can then be merged

**Closed** 2017-01-29 04:53 UTC
