### ISSUE TITLE
rewrite VT to use API

### ISSUE THREAD

**Issue by showerst** [openstates/openstates#2554] opened 2018-10-25 14:43 UTC
Thought i'd start a list of states who've changed their websites and need new scrapers, so that we don't duplicate work come rewrite time.

- [x] AK
- [x] MT
- [ ] VT -- Not actually broken, but they released an API so we should switch to it, lower priority

**Comment by showerst** [comment] 2018-11-21 19:46
MT PR'd by @jmcarp --  https://github.com/openstates/openstates/pull/2664

**Comment by showerst** [comment] 2018-11-29 15:38
I'm working on AK on the branch tim/2018/ak-new

**Comment by Kreloc** [comment] 2019-01-29 19:16
The Alaska Legislature does have an API. It does not require a key at this time.
It defaults to returning data in xml but can also return it in json.

This webpage lets you preview the output you can get from it.
www.akleg.gov/apptester.html

Documentation:
http://www.akleg.gov/basis/BasisPublicServiceAPI.pdf

**Comment by greatseth** [comment] 2019-02-21 17:28
Hey all,

The lack of AK data for 2019 brought this to my attention recently. How does the situation look? Please let me know if I can help.

Thanks!

**Comment by showerst** [comment] 2019-02-21 17:38
I actually have a (non-api) branch for AK that i've been playing w/ for a while, but i haven't done enough QA on the data quality to push it live here. If you'd like to help out, check out -- https://github.com/openstates/openstates/tree/tim/2018/ak-new

Do an Alaska bill scrape (pupa update ak bills --scrape) and maybe spot check some bills? I've been meaning to do it but pretty slammed at day job. But if I can get someone to verify the data, cleaning up the code for flake8 should be no problem.

**Comment by jamesturk** [comment] 2020-01-14 18:11
updated issue name to reflect remaining task

**Comment by jamesturk** [comment] 2020-01-14 21:00
noticed this was a dupe of #2040

**Closed by jamesturk** 2020-01-14 21:00 UTC
