### ISSUE TITLE
CA: Duplicate bills 

### ISSUE THREAD

**Issue by ilyagerner** [openstates/openstates#2880] opened 2019-02-22 19:08 UTC
State: CA

For the current session (20192020), API V2 is returning duplicate Assembly bills in situations where there exists a Senate bill with the same bill number.

For example:
[SB 73](https://openstates.org/ca/bills/?query=SB+73&session=20192020&classification=&sponsor=) is correctly reported as the Budget Act of 2019.
[AB 73](https://openstates.org/ca/bills/?query=AB+73&session=20192020&classification=&sponsor=) is correctly reported as "Privacy: lodging and common carriers: state emergencies: Disaster Response-Emergency Operations Account."
But there is also a second AB 73, which is erroneously shown as the Budget Act of 2019. (The [CA website](https://leginfo.legislature.ca.gov/faces/billSearchClient.xhtml?session_year=20192020&bill_number=73&house=Both&author=All&lawCode=All) indicates that there should only be a SB73 Budget bill and a AB73 privacy bill.) This leads to an error since the query [{bill(jurisdiction: “California”, session: “20192020”, identifier: “AB 73”) {id}} ](https://openstates.org/graphql?operationName=null&query=%7B%0A%20%20bill(jurisdiction%3A%20%22California%22%2C%20session%3A%20%2220192020%22%2C%20identifier%3A%20%22AB%2076%22)%20%7B%0A%20%20%20%20id%0A%20%20%7D%0A%7D%0A) should return a unique bill.

The solution seems to be to prune the duplicate AB bills, dropping the ones that have the same title and number as the S bills, leaving the ones that have the same number but a unique title.

**Comment by showerst** [comment] 2019-02-22 19:20
@jamesturk FWIW the scraper output seems ok here, so either some weird data got in or this is an api layer bug. 

It seems to be happening for many California AB-s, but not all.

**Comment by estaub** [comment] 2019-02-23 00:46
@showerst Did you happen to see a correlation with the bill number?  I wonder if CA messed up for a while, putting out AB's when they meant SB's, and later fixed it.

**Comment by mhedblom** [comment] 2019-02-27 05:53
I see this problem with "AB 2". Search for "AB 2" gets the duplicate error
```{
  bill(jurisdiction: "California", session: "20192020", identifier: "AB 2") {
        id  identifier  title  }}
```
Error:
```{
  "errors": [
    {
      "message": "get() returned more than one Bill -- it returned 2!",
```

But "SB 2" works correctly:
```{
  bill(jurisdiction: "California", session: "20192020", identifier: "SB 2") {
        id  identifier  title  }}
```

Searching for AB2 using the the Subject:
```{
  bills(
    jurisdiction: "California", chamber: "lower", session: "20192020", classification:"bill", 
    subject: "Community colleges: California College Promise.",
    first:10

  )
  { 
    totalCount
    edges {
      node {
        id
        identifier
        title
        subject
      }    }  } }
```

 finds just one record:

```{
  "data": {
    "bills": {
      "totalCount": 1,
      "edges": [
        {
          "node": {
            "id": "ocd-bill/b89511b4-ad4d-4c7c-ab42-fb99fc8be086",
            "identifier": "AB 2",
            "title": "Community colleges: California College Promise.",
            "subject": [
              "Community colleges: California College Promise."
            ]
          }        }      ]    }  }}
```

**Comment by ilyagerner** [comment] 2019-03-04 02:25
I'm seeing 1720 California bill identifiers that are duplicated (searching only the universe of bills that are from 20192020 session and have the classification "bill"). 

Some are like the issue described above where there is both a legitimate AB bill and an AB bill that erroneously duplicates an SB bill.

But there are also bill IDs that are pure dupes, such as [SB 743](https://openstates.org/ca/bills/?query=SB+743&session=20192020&classification=&sponsor=), which is reported twice. AB 743 perfectly normal.

This is a [list of the duplicates](https://gist.github.com/ilyagerner/e5da554e1efae8f589d56e896ed1b75d#file-duplicates-py).

**Comment by ilyagerner** [comment] 2019-03-04 18:11
@mhedblom, Interesting, if you run the latter query without the chamber argument, you'll be back to having two bills again: each with the same title, same AB-2 identifier, same subject, but one that's identified as coming from the Senate and one from the Assembly.

I see 1741 such duplicate bills.

The "wrong" one seems to be the bill where the fromOrganization doesn't match the bill identifier. That is the bill ID is AB- or AJR- or ACR- something but there exists a version with the same ID that lists fromOrganization as the Senate.

[duplicate_bills.txt](https://github.com/openstates/openstates/files/2927621/duplicate_bills.txt) is a list of the duplicate bills.
[to_purge.txt](https://github.com/openstates/openstates/files/2927622/to_purge.txt) is a list of dictionaries, each containing the openstatesID of the "wrong" bill; one where the ID doesn't match the organization.

[Jupyter notebook](https://github.com/ilyagerner/scrapbook/blob/master/california_duplication.ipynb) for replication.

**Comment by estaub** [comment] 2019-03-04 18:47
@mhedblom @ilyagerner Same question as I asked Tim earlier, more broadly: _do you see any pattern in which bills get messed up_ and which ones don't?

Here's some grist - things you might see:

* only bills from some time period are duplicated
* only bills that have "crossed over" are duplicated, i.e., they passed in the Senate and now the Assembly is considering them 
* only bills that have had some joint action (e.g., study by a joint committee) are duplicated

**Comment by ilyagerner** [comment] 2019-03-04 21:15
@estaub I'll report whatever I find but I should note that there are are also lots of "pure duplicates"; that is, bills for which we have two AB's without there being an SB with the equivalent identifier. This is contra to my initial expectation.

For example:

`{'data': {'bills': {'totalCount': 2,
   'edges': [{'bill': {'id': 'ocd-bill/3cee18b5-743c-4afa-a05f-f428611621af',
      'identifier': 'AB 1534',
      'title': 'Housing: homelessness.',
      'classification': ['bill'],
      'updatedAt': '2019-03-01 18:09:39.606284+00:00',
      'createdAt': '2019-03-01 18:09:39.606260+00:00',
      'fromOrganization': {'id': 'ocd-organization/e70e812e-44d2-46b0-9eae-2f3b9a1d5150',
       'name': 'Assembly'}}},
    {'bill': {'id': 'ocd-bill/20ec1e34-6935-44dc-95c3-580133747474',
      'identifier': 'AB 1534',
      'title': 'Housing: homelessness.',
      'classification': ['bill'],
      'updatedAt': '2019-02-26 18:09:17.512475+00:00',
      'createdAt': '2019-02-23 18:09:19.806095+00:00',
      'fromOrganization': {'id': 'ocd-organization/98623fa0-f9c3-47ae-80bb-51465349ed71',
       'name': 'Senate'}}}]}}}`

There is no SB 1534.

**Comment by ilyagerner** [comment] 2019-03-04 21:27
As for time period, the bad bills -- defined as those that have a "fromOrganization" of "Senate" and an "identifier" that begins with "A" OR a a "fromOrganization" of "Assembly" and an "identifier" that begins with "S" -- were created in a narrow time period:
```

{datetime.datetime(2019, 2, 23, 0, 0): 310,
 datetime.datetime(2019, 2, 20, 0, 0): 639,
 datetime.datetime(2019, 2, 27, 0, 0): 745,
 datetime.datetime(2019, 2, 16, 0, 0): 37,
 datetime.datetime(2019, 2, 22, 0, 0): 4,
 datetime.datetime(2019, 2, 26, 0, 0): 6}
```

**Comment by estaub** [comment] 2019-03-04 21:53
> 
> ```
> {'data': {'bills': {'totalCount': 2,
>    'edges': [{'bill': {'id': 'ocd-bill/3cee18b5-743c-4afa-a05f-f428611621af',
>       'identifier': 'AB 1534',
>       'title': 'Housing: homelessness.',
>       'classification': ['bill'],
>       'updatedAt': '2019-03-01 18:09:39.606284+00:00',
>       'createdAt': '2019-03-01 18:09:39.606260+00:00',
>       'fromOrganization': {'id': 'ocd-organization/e70e812e-44d2-46b0-9eae-2f3b9a1d5150',
>        'name': 'Assembly'}}},
>     {'bill': {'id': 'ocd-bill/20ec1e34-6935-44dc-95c3-580133747474',
>       'identifier': 'AB 1534',
>       'title': 'Housing: homelessness.',
>       'classification': ['bill'],
>       'updatedAt': '2019-02-26 18:09:17.512475+00:00',
>       'createdAt': '2019-02-23 18:09:19.806095+00:00',
>       'fromOrganization': {'id': 'ocd-organization/98623fa0-f9c3-47ae-80bb-51465349ed71',
>        'name': 'Senate'}}}]}}}
> ```

Note the difference in times.  I'm guessing that for some reason the pseudo-ids changed; I'll see if I can see anything.

**Comment by estaub** [comment] 2019-03-06 15:05
@jamesturk I just checked the query reported in https://github.com/openstates/openstates/issues/2880#issuecomment-467734113,

```graphql
{
  bill(jurisdiction: "California", session: "20192020", identifier: "AB 2") {
    id
    identifier
    title
  }
}
```
and it's still failing with `...it returned 2!`.  So I guess there's more cleanup to do.  Sigh.

**Comment by jamesturk** [comment] 2019-03-06 20:54
I've done a full wipe of these, if they don't come back in the next scrape
I think we can close this.

**Comment by estaub** [comment] 2019-03-08 02:38
Some/most "it returned 2!" instances are fixed, but this one (at a minimum) is not:
```graphql
{
  bill(jurisdiction: "California", session: "20192020", identifier: "AB 73") {
    id
    identifier
    title
  }
}
```

**Comment by estaub** [comment] 2019-03-08 02:40
When I run the scraper, I only get one "AB 73".

**Comment by ilyagerner** [comment] 2019-03-08 14:25
I'm seeing 743 duplicate bills. Some are as a result of an older bill being quashed by a newly created bill in the wrong chamber. For example, here is SB-405, which was correctly identified as a Senate bill on 2019-02-21, but then wrongly created as an Assembly bill on 2019-03-07:

```
{'bill': {'id': 'ocd-bill/24027910-2c09-467d-a71c-96e81b312d3e', 'identifier': 'SB 405', 'title': 'Solid waste: reclaimed asphalt pavement: pilot project: the County of Los Angeles.', 'classification': ['bill'], 'updatedAt': '2019-02-24 18:08:10.868999+00:00', 'createdAt': '2019-02-21 18:07:30.893877+00:00', 'fromOrganization': {'id': 'ocd-organization/98623fa0-f9c3-47ae-80bb-51465349ed71', 'name': 'Senate'}}}
{'bill': {'id': 'ocd-bill/c5054506-ea41-435f-aa63-efaff7cc7f78', 'identifier': 'SB 405', 'title': 'Solid waste: reclaimed asphalt pavement: pilot project: the County of Los Angeles.', 'classification': ['bill'], 'updatedAt': '2019-03-08 18:09:25.496726+00:00', 'createdAt': '2019-03-07 06:09:46.592127+00:00', 'fromOrganization': {'id': 'ocd-organization/e70e812e-44d2-46b0-9eae-2f3b9a1d5150', 'name': 'Assembly'}}}
```

Then there are bills where we're simultaneously creating an Assembly and a Senate version. E.g., AB 960:

```
{'bill': {'id': 'ocd-bill/1038d19e-4a17-4469-aa1f-de7942a53f92',
    'identifier': 'AB 960',
    'title': 'CalWORKs: homeless assistance.',
    'classification': ['bill'],
    'updatedAt': '2019-03-07 18:09:09.239004+00:00',
    'createdAt': '2019-03-07 18:09:09.238977+00:00',
    'fromOrganization': {'id': 'ocd-organization/e70e812e-44d2-46b0-9eae-2f3b9a1d5150',
     'name': 'Assembly'}}},
  {'bill': {'id': 'ocd-bill/8e3a983b-455b-4a5a-bab3-aa9b9f4ae9c5',
    'identifier': 'AB 960',
    'title': 'CalWORKs: homeless assistance.',
    'classification': ['bill'],
    'updatedAt': '2019-03-07 06:09:58.067266+00:00',
    'createdAt': '2019-03-07 06:09:58.067242+00:00',
    'fromOrganization': {'id': 'ocd-organization/98623fa0-f9c3-47ae-80bb-51465349ed71',
     'name': 'Senate'}}}
```

**Comment by ilyagerner** [comment] 2019-03-08 15:53
So I think we have two problems here.

The bigger issue is that the we're still creating duplicates. Here's a [dictionary ](https://gist.github.com/ilyagerner/98ee5bdfbdeba415b7d8e288c8fbf559) of the duplicates that have an identical title and identifier. The key is the identifier, the value is a list containing the details of the two bills that share the identifier.

**Comment by ilyagerner** [comment] 2019-03-08 16:51
All of the "wrong" (identifier differs from the 'fromOrganization') duplicates (743 pure dupes + 9 different title dupes = 752) were [created yesterday and today](https://github.com/ilyagerner/scrapbook/blob/master/california_duplicates.ipynb):

```
{datetime.datetime(2019, 3, 7, 0, 0): 748,
 datetime.datetime(2019, 3, 8, 0, 0): 4}
```

**Comment by estaub** [comment] 2019-03-08 17:28
@ilyagerner Thanks for all the research!

Some notes from the dictionary:
* it's happening with both "SB" and "AB" bills
* the `from_organization` is wrong on the second one, presumably meaning that a wrong chamber is still leading to failure to resolve against the correct original

I'm retesting the scraper to try to see what else I missed.

**Comment by estaub** [comment] 2019-03-08 18:11
While waiting for the 100MB+ to be processed, I did some more checking of Ilya's [dictionary](https://gist.github.com/ilyagerner/98ee5bdfbdeba415b7d8e288c8fbf559).   I spot-checked a few duplicate bills for status on the CA website, and none of them are "crossed over" to the other house; in fact, they are all still in committee.

**Comment by showerst** [comment] 2019-03-08 18:37
I won't be able to a local scrape on my computer today; but it seems like the from_organization being wrong would cause all of these problems.

Looking at the code I don't see how it's getting set wrongly though; super weird.

**Comment by showerst** [comment] 2019-03-08 18:46
I have a mysql server with last night's scrape on it; just to rule out a source data issue, it looks like the source is good.

```
 SELECT * FROM bill_tbl WHERE bill_id = '201920200SB405' LIMIT 1;
+----------------+--------------+-------------+--------------+-------------+---------------+--------------+--------------+---------------------+-------------+------------------------+------------+-----------+---------------------+------------------+-----------------------+---------------+----------------------+---------------------+
| bill_id        | session_year | session_num | measure_type | measure_num | measure_state | chapter_year | chapter_type | chapter_session_num | chapter_num | latest_bill_version_id | active_flg | trans_uid | trans_update        | current_location | current_secondary_loc | current_house | current_status       | days_31st_in_print  |
+----------------+--------------+-------------+--------------+-------------+---------------+--------------+--------------+---------------------+-------------+------------------------+------------+-----------+---------------------+------------------+-----------------------+---------------+----------------------+---------------------+
| 201920200SB405 | 20192020     | 0           | SB           |         405 | Introduced    | NULL         | NULL         | NULL                | NULL        | 20190SB40599INT        | Y          | HS_INT    | 2019-02-28 13:54:53 | CS59             | Committee             | Senate        | In Committee Process | 2019-03-23 00:00:00 |
+----------------+--------------+-------------+--------------+-------------+---------------+--------------+--------------+---------------------+-------------+------------------------+------------+-----------+---------------------+------------------+-----------------------+---------------+----------------------+---------------------+
1 row in set (0.00 sec)
```

**Comment by estaub** [comment] 2019-03-08 20:46
@jamesturk I'm afraid I'm stumped.  I've run a scrape and both comprehensively searched for wrong chamber in the `from_organization`, and spot-checked a few of the dupes from Ilya's dictionary, above.  All are correct.  For example, here's the beginning of one:

```json
{
    "legislative_session": "20192020", "identifier": "SB334",
    "title": "Healing arts: clinical laboratories.",
    "from_organization": "~{\"classification\": \"upper\"}", "classification": ["bill"],
    "subject": ["Healing arts: clinical laboratories."], "abstracts": [
```

Either I've missed something, or CA is transiently screwing up and happens to be ok right now, or the problem is downstream from the scraper.

**Comment by ilyagerner** [comment] 2019-03-08 23:47
Looked at an older data dump from CA and didn't see any issues on their end either. Eventually I will figure out how to run Docker on Windows 10 Home so I can help with debugging scrappers (but apparently today is not that day).

**Comment by ilyagerner** [comment] 2019-03-09 23:57
I wanted to see if there were duplication problems with other states. 

California has 752 duplicates, Washington State has 300. [No problems elsewhere.
](https://github.com/ilyagerner/scrapbook/blob/master/Analysis%20of%20Duplicates%20in%20Openstates.ipynb)
Alaska doesn't have any bills for the current session, but that's a different issue.

**Comment by estaub** [comment] 2019-03-10 06:34
@ilyagerner It _might_ be useful to try to figure out what distinguishes the 752 duplicated bills from the rest.

**Comment by jamesturk** [comment] 2019-03-12 04:10
I think it'd be good to introduce code that logs when the CA scraper tries to save a bill w/ chamber=upper & identifier starts with 'A' (and vice versa) and doesn't yield this bill -- that'll fix the issue in the short term (and let us figure out where it's coming from)

I'll try to find time to this week but have pretty limited time the next day or two, but if someone wants to run w/ this I'd gladly merge it as a temporary fix

**Comment by estaub** [comment] 2019-03-12 15:53
I'm jammed up till late Wednesday - I'll do it then or Thursday if still happening.  Note that the trans-chamber ghost bills are being updated, e.g.:
```json
        {
          "node": {
            "identifier": "SB 515",
            "fromOrganization": {
              "name": "Assembly"
            },
            "createdAt": "2019-03-07 06:09:20.388751+00:00",
            "updatedAt": "2019-03-11 17:09:28.545569+00:00"
          }
        }
```

**Comment by jamesturk** [comment] 2019-03-13 02:33
added the skip code and re-purged DB of these (again) these will be working for now, we'll have to see if a new scrape changes anything

**Closed** 2019-03-29 06:19 UTC
